version: "3.6"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    expose:
      - 2181
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: >-
        livelock_broken:8:1,
        livelock_working_1_7:8:1,
        livelock_working_1_8:8:1
    expose:
      - 9092
    depends_on:
      - zookeeper
